### ISSUE TITLE
执行 hexo d 的时候报错了

### ISSUE THREAD

**Issue by GJCheng-Lab** [du5/hexo-deployer-oss-aliyun#1]
FATAL YAMLException: duplicated mapping key (132:1)

 130 |
 131 | # https://oss.console.aliyun.co ...
 132 | deploy:
-------^
 133 |     type: aliyun-oss
 134 |     region: lkjokj.oss-cn-shan ...
    at generateError (/home/pi/myblog/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/home/pi/myblog/node_modules/js-yaml/lib/loader.js:187:9)
    at storeMappingPair (/home/pi/myblog/node_modules/js-yaml/lib/loader.js:358:7)
    at readBlockMapping (/home/pi/myblog/node_modules/js-yaml/lib/loader.js:1173:9)
    at composeNode (/home/pi/myblog/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/home/pi/myblog/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/home/pi/myblog/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/home/pi/myblog/node_modules/js-yaml/lib/loader.js:1714:19)
    at Hexo.yamlHelper (/home/pi/myblog/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/home/pi/myblog/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/pi/myblog/node_modules/bluebird/js/release/method.js:15:34)
    at /home/pi/myblog/node_modules/hexo/lib/hexo/render.js:75:22
    at tryCatcher (/home/pi/myblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/myblog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/pi/myblog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/pi/myblog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/pi/myblog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/pi/myblog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/pi/myblog/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/pi/myblog/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/myblog/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:464:21) {
  reason: 'duplicated mapping key',
  mark: {

**Comment by du5** [comment]
yaml 配置文件格式写错了

**Comment by GJCheng-Lab** [comment]
> yaml 配置文件格式写错了

嗖嘎，yaml里有一个空的deploy，删了就可以了，谢谢

**Comment by GJCheng-Lab** [comment]
> yaml 配置文件格式写错了

但是又有新错误了
pi@raspberrypi:~/myblog $ hexo d
INFO  Validating config
ERROR Deployer not found: aliyun-oss 
神奇了

**Comment by du5** [comment]
aliyunoss

**Comment by GJCheng-Lab** [comment]
> aliyunoss

OK！可以了，谢谢！
